In [2]:
import pandas as pd

In [3]:

schema_df= pd.read_csv(r'C:\Users\Charuta\Codes\Python\Schema.csv')
schema_df

,Column_Name,Data_Type,Description,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Age,Integer,Age of the individual in years,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,MCV_fL,Float,Mean Corpuscular Volume in femtoliters (red bl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Gender,String,Gender of the individual (Male/Female/Other),NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Transferrin_Saturation_pct,Float,Percentage of transferrin saturation (iron tra...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BMI,Float,Body Mass Index (kg/m²),NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
56,Restless_Legs,String,Presence of restless legs (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,Night_Sweats,String,Presence of night sweats (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,Energy_Level,String,Energy level (Low,Medium,High),NaN,NaN,NaN,NaN,NaN
59,Sleep_Quality,String,Sleep quality (Poor,Average,Good),NaN,NaN,NaN,NaN,NaN
60,Deficiency,String,Type of deficiency diagnosed (Iron,Vitamin D,Calcium,Magnesium,Folate,Vitamin B12,Zinc,None)

In [4]:
schema_df.drop(index=  [1,3,5,7,9,11,13,15,32,34,36,38,40,42,44,46,48,50],inplace=True)
schema_df

,Column_Name,Data_Type,Description,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Age,Integer,Age of the individual in years,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Gender,String,Gender of the individual (Male/Female/Other),NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BMI,Float,Body Mass Index (kg/m²),NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Geographic_Region,String,Region type (Polar/Cold,Tropical,Temperate,Subtropical),NaN,NaN,NaN,NaN
8,Pregnancy_Status,String,Whether the individual is pregnant (Yes/No/N/A),NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Diet_Type,String,Dietary preference (Omnivore,Vegetarian,Vegan,Pescatarian),NaN,NaN,NaN,NaN
12,Smoking_Status,String,Smoking habit (Never,Former,Current),NaN,NaN,NaN,NaN,NaN
14,Alcohol_Consumption,String,Alcohol intake (None,Occasional,Moderate,Heavy),NaN,NaN,NaN,NaN
16,Sun_Exposure,String,Level of sun exposure (Low,Moderate,High),NaN,NaN,NaN,NaN,NaN
17,Fatigue,String,Presence of fatigue (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Physical_Activity_Level,String,Activity level (Sedentary,Light,Moderate,Active),NaN,NaN,NaN,NaN
19,Pallor,String,Presence of pallor (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Stress_Level,String,Stress level (Low,Moderate,High),NaN,NaN,NaN,NaN,NaN
21,Shortness_of_Breath,String,Presence of shortness of breath (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Chronic_Condition,String,Chronic condition present (Diabetes,CKD,Hypertension,etc.),NaN,NaN,NaN,NaN
23,Cold_Intolerance,String,Presence of cold intolerance (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Medication_Use,String,Medication type (Steroids,Antacids/PPIs,Diuretics,etc.),NaN,NaN,NaN,NaN
25,Bone_Pain,String,Presence of bone pain (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Recent_Blood_Loss,String,Recent blood loss (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Muscle_Weakness,String,Presence of muscle weakness (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Family_History_of_Deficiency,String,Family history of deficiency (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Frequent_Illness,String,Frequent illness occurrence (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Digestive_Issues,String,Presence of digestive issues (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Hair_Loss,String,Presence of hair loss (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Tingling_Numbness,String,Presence of tingling/numbness (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Memory_Cognitive_Issues,String,Presence of memory/cognitive issues (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Balance_Problems,String,Presence of balance problems (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Mood_Swings,String,Presence of mood swings (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Muscle_Cramps,String,Presence of muscle cramps (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Dental_Issues,String,Presence of dental issues (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Brittle_Nails,String,Presence of brittle nails (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Anxiety_and_Poor_Sleep,String,Presence of anxiety/poor sleep (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,Frequent_Headaches,String,Presence of frequent headaches (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,Loss_of_Appetite,String,Presence of appetite loss (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,Slow_Wound_Healing,String,Presence of slow wound healing (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,Loss_of_Taste_Smell,String,Presence of taste/smell loss (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,Mouth_Sores,String,Presence of mouth sores (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,Tongue_Swelling,String,Presence of tongue swelling (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,Restless_Legs,String,Presence of restless legs (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,Night_Sweats,String,Presence of night sweats (Yes/No),NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,Energy_Level,String,Energy level (Low,Medium,High),NaN,NaN,NaN,NaN,NaN
59,Sleep_Quality,String,Sleep quality (Poor,Average,Good),NaN,NaN,NaN,NaN,NaN
60,Deficiency,String,Type of deficiency diagnosed (Iron,Vitamin D,Calcium,Magnesium,Folate,Vitamin B12,Zinc,None)

In [5]:
df= pd.read_csv(r'C:\Users\Charuta\Codes\Python\Health Screen\Data\unclean enriched_deficiency_dataset.csv')
df.drop(columns= ['Iron_Intake_mg', 'VitaminD_Intake_IU','B12_Intake_mcg', 'Calcium_Intake_mg', 'Magnesium_Intake_mg', 'Zinc_Intake_mg', 'Folate_Intake_mcg', 'Serum_Iron_ugdL', 'Serum_Ferritin_ngmL', 'Hemoglobin_gdL', 'MCV_fL', 'Transferrin_Saturation_pct', 'Serum_VitD_ngmL', 'Serum_B12_pgmL', 'Serum_Folate_ngmL', 'Serum_Calcium_mgdL', 'Serum_Magnesium_mgdL', 'Serum_Zinc_ugdL'], inplace = True)
df.dropna(axis= 'index',how='all') #this is used when you want to drop indexes with all values missing
df.dropna(axis= 'columns', how= 'all')
# Step 1 — Fill known nullable columns with 'None'
cat_null_cols = [
    'Pregnancy_Status', 'Alcohol_Consumption',
    'Chronic_Condition', 'Medication_Use', 'Digestive_Issues'
]
df[cat_null_cols] = df[cat_null_cols].fillna('None')

# Step 2 — Fill any remaining Yes/No columns with 'No'
# Empty symptom = symptom not present = No
binary_null_cols = [
    'Fatigue', 'Pallor', 'Shortness_of_Breath', 'Cold_Intolerance',
    'Bone_Pain', 'Muscle_Weakness', 'Frequent_Illness', 'Hair_Loss',
    'Tingling_Numbness', 'Memory_Cognitive_Issues', 'Balance_Problems',
    'Mood_Swings', 'Muscle_Cramps', 'Dental_Issues', 'Brittle_Nails',
    'Anxiety_and_Poor_Sleep', 'Frequent_Headaches', 'Loss_of_Appetite',
    'Slow_Wound_Healing', 'Loss_of_Taste_Smell', 'Mouth_Sores',
    'Tongue_Swelling', 'Restless_Legs', 'Night_Sweats',
    'Recent_Blood_Loss', 'Family_History_of_Deficiency'
]
df[binary_null_cols] = df[binary_null_cols].fillna('No')

# Step 3 — Drop rows where target is still null
df.dropna(subset=['Deficiency'], inplace=True)

# Step 4 — Final check
print("Remaining nulls:")
print(df.isnull().sum()[df.isnull().sum() > 0])
binary_cols = [
    'Fatigue', 'Pallor', 'Shortness_of_Breath', 'Cold_Intolerance',
    'Bone_Pain', 'Muscle_Weakness', 'Frequent_Illness', 'Hair_Loss',
    'Tingling_Numbness', 'Memory_Cognitive_Issues', 'Balance_Problems',
    'Mood_Swings', 'Muscle_Cramps', 'Dental_Issues', 'Brittle_Nails',
    'Anxiety_and_Poor_Sleep', 'Frequent_Headaches', 'Loss_of_Appetite',
    'Slow_Wound_Healing', 'Loss_of_Taste_Smell', 'Mouth_Sores',
    'Tongue_Swelling', 'Restless_Legs', 'Night_Sweats',
    'Recent_Blood_Loss', 'Family_History_of_Deficiency'
]
for col in binary_cols:
    df[col] = df[col].map({'Yes':1, 'No':0})
print("Binary Columns done!")
print(df[binary_cols].head)

df['Energy_Level'] = df['Energy_Level'].map({'Low': 0, 'Medium': 1, 'High': 2})
df['Sleep_Quality'] = df['Sleep_Quality'].map({'Poor': 0, 'Average': 1, 'Good': 2})
df['Sun_Exposure'] = df['Sun_Exposure'].map({'Low': 0, 'Moderate': 1, 'High': 2})
df['Stress_Level'] = df['Stress_Level'].map({'Low': 0, 'Moderate': 1, 'High': 2})
df['Physical_Activity_Level'] = df['Physical_Activity_Level'].map({'Sedentary': 0, 'Light': 1, 'Moderate': 2, 'Active': 3})
df['Digestive_Issues']    =df['Digestive_Issues'].map({'None':0, 'Occasional':1, 'Frequent':2})
print("Ordered columns encoded!")

one_hot_cols = [
    'Gender', 'Geographic_Region', 'Diet_Type',
    'Smoking_Status', 'Alcohol_Consumption',
    'Chronic_Condition', 'Medication_Use', 'Pregnancy_Status'
]
df = pd.get_dummies(df, columns=one_hot_cols, drop_first=False)

print("One hot encoding done!")
print("New shape:", df.shape)

Remaining nulls:
Series([], dtype: int64)
Binary Columns done!
<bound method NDFrame.head of      Fatigue  Pallor  Shortness_of_Breath  Cold_Intolerance  Bone_Pain  \
0          0       0                    0                 1          0
1          1       1                    0                 0          1
2          0       0                    0                 0          0
3          1       0                    0                 0          1
4          0       0                    0                 0          0
..       ...     ...                  ...               ...        ...
495        0       0                    0                 0          0
496        0       0                    0                 0          0
497        1       0                    0                 0          1
498        0       1                    0                 0          0
499        1       1                    1                 0          0

     Muscle_Weakness  Frequent_Illness  Hair_Loss  Tingling_Numbness  \
0                  1                 0          0                  1
1                  0                 0          0                  0
2                  1                 1          0                  0
3                  1                 1          0                  0
4                  0                 0          1                  0
..               ...               ...        ...                ...
495                1                 0          0                  0
496                0                 0          0                  1
497                0                 1          0                  0
498                1                 1          0                  0
499                0                 1          0                  1

     Memory_Cognitive_Issues  ...  Frequent_Headaches  Loss_of_Appetite  \
0                          0  ...                   0                 0
1                          0  ...                   0                 0
2                          0  ...                   0                 0
3                          0  ...                   0                 0
4                          0  ...                   1                 0
..                       ...  ...                 ...               ...
495                        0  ...                   1                 0
496                        1  ...                   0                 0
497                        1  ...                   0                 0
498                        1  ...                   0                 0
499                        1  ...                   1                 0

     Slow_Wound_Healing  Loss_of_Taste_Smell  Mouth_Sores  Tongue_Swelling  \
0                     1                    0            0                0
1                     0                    0            0                0
2                     0                    0            0                0
3                     0                    0            0                0
4                     0                    0            0                0
..                  ...                  ...          ...              ...
495                   0                    0            0                0
496                   0                    1            0                0
497                   0                    0            0                0
498                   0                    0            0                0
499                   1                    0            0                0

     Restless_Legs  Night_Sweats  Recent_Blood_Loss  \
0                1             1                  0
1                1             0                  0
2                0             0                  0
3                0             1                  0
4                1             0                  0
..             ...           ...                ...
495              0             0                  0
496              0             1                  0
497              1             0                  0
498              0             0                  1
499              0             0                  0

     Family_History_of_Deficiency
0                               1
1                               0
2                               0
3                               1
4                               1
..                            ...
495                             0
496                             1
497                             0
498                             0
499                             0

[462 rows x 26 columns]>
Ordered columns encoded!
One hot encoding done!
New shape: (462, 69)

In [6]:
df.to_csv(r"C:\Users\Charuta\Downloads\final_deficiency_dataset.csv", index=False)
schema_df.to_csv(r"C:\Users\Charuta\Downloads\dataset_schema.csv", index=False)
print("Schema saved successfully!")

Schema saved successfully!